In [1]:
import pandas as pd
import seaborn as sns

# Dataset Load

In [2]:
df = pd.read_csv('merged_data.csv')

# See  dataset first 5 rows

In [3]:
# See the first 5 rows
df.head().T

                 0           1           2           3           4
Date    2000-01-01  2000-01-01  2000-01-01  2000-01-01  2000-01-01
Scrip          ACI      ALLTEX    AMBEEPHA  AMCL(PRAN)   APEXFOODS
Open     12.674539         4.7        31.2        26.0       30.05
High     13.774594        4.75        32.0        27.0        30.5
Low      12.674539         4.7        31.2        26.0       29.95
Close    13.631108         4.7        31.6      26.525      30.175
Volume       19850       17500        1150        2500         850

# See  dataset last 5 rows

In [4]:
# See the Last 5 rows
df.tail().T

           1381566     1381567     1381568     1381569     1381570
Date    2025-02-26  2025-02-26  2025-02-26  2025-02-26  2025-02-26
Scrip   WONDERTOYS         YPL  ZAHEENSPIN    ZAHINTEX  ZEALBANGLA
Open          33.5        14.0         8.2         5.3        85.9
High          33.5        14.0         8.6         5.3        85.9
Low           27.7        13.7         8.1         5.1        83.3
Close         27.7        13.9         8.3         5.2        84.4
Volume       12663      112630     1614597      141507        1112

# Dataset Dimensions

In [5]:
# Datast shape
df.shape

(1381571, 7)

# Dataset Information

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1381571 entries, 0 to 1381570
Data columns (total 7 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   Date    1381571 non-null  object
 1   Scrip   1381571 non-null  object
 2   Open    1381571 non-null  float64
 3   High    1381571 non-null  float64
 4   Low     1381571 non-null  float64
 5   Close   1381571 non-null  float64
 6   Volume  1381571 non-null  int64
dtypes: float64(4), int64(1), object(2)
memory usage: 73.8+ MB

# Statistical Summary

In [11]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Open,1381571.0,1.054704e+02,9.664946e+02,-0.274725,12.480926,26.296000,61.157025,1.037500e+06
High,1381571.0,1.068120e+02,9.678045e+02,0.000000,12.700000,26.740646,62.278239,1.037500e+06
Low,1381571.0,1.040851e+02,9.653695e+02,-0.366300,12.244900,25.750000,60.000000,1.037500e+06
Close,1381571.0,1.052271e+02,9.663991e+02,0.004381,12.426304,26.162435,60.952713,1.037500e+06
Volume,1381571.0,4.829822e+07,6.909170e+08,0.000000,20637.000000,123500.000000,497629.500000,5.607908e+10

# Dataset Columns

In [12]:
df.columns

Index(['Date', 'Scrip', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')